### PR TITLE
fix(alerting): Now default to read batched data timestamp in seconds …

### PR DESCRIPTION
**Pull request by joe-bethke**
…in ASA. Optionally use ms based on value of telemetry field.

This is an update to one of our user-defined JS functions on our alerting ASA jobs. Below is the change in a more legible format:

before:
```javascript
function main(record, dataPoint, isBatched) {
    let iotHubTimestamp = record.EventEnqueuedUtcTime;
    if (isBatched == 'true' && record.hasOwnProperty('data') && record.hasOwnProperty('channels')) {
        let lowerCaseChannels = record.channels.map(channel => channel.toLowerCase());
        let timestampIndex = lowerCaseChannels.indexOf('unixts');
        if (timestampIndex == -1) {
            return iotHubTimestamp;
        }
        else {
            // The timestamp in the data point is a millisecond unix timestamp, and must be converted to 1970-01-01T00:00:00.000Z format
            let receviedTime = new Date(dataPoint[timestampIndex]);
            return receviedTime.toISOString();
        }
    }
    else {
        return iotHubTimestamp;
    }
}
```

after:
```javascript
function main(record, dataPoint, isBatched) {
    let iotHubTimestamp = record.EventEnqueuedUtcTime;
    if (isBatched == 'true' && record.hasOwnProperty('data') && record.hasOwnProperty('channels')) {
        let lowerCaseChannels = record.channels.map(channel => channel.toLowerCase());
        let timestampIndex = lowerCaseChannels.indexOf('unixts');
        if (timestampIndex == -1) {
            return iotHubTimestamp;
        }
        else {
            /*
                PR CHANGES START HERE
            */

            let timestampValue = dataPoint[timestampIndex];
            let timestampMeasurementIndex = lowerCaseChannels.indexOf('unixtsmeasurement');

            // default the measurement to seconds if we're using the data point timestamp and the measurement field was not given
            let timestampMeasurement = timestampMeasurementIndex != -1
                ? dataPoint[timestampMeasurementIndex]
                : 's';

            switch (timestampMeasurement) {
                case 's':  // seconds
                    timestampValue *= 1000;  // convert to ms
                    break;
            }

            /*
                PR CHANGES END HERE
            */

            // The timestamp in the data point is a millisecond unix timestamp, and must be converted to 1970-01-01T00:00:00.000Z format
            let receviedTime = new Date(timestampValue);
            return receviedTime.toISOString();
        }
    }
    else {
        return iotHubTimestamp;
    }
}
```

### CODE REVIEW

**Comment by kyleestes** [comment]
> What is the nature of the changes to the webui code in this PR? It didn't seem related to the PR as it is titled, but maybe I'm just missing it.

Never mind -- I need to read the PR body not just the title

**Comment by kyleestes** [comment]
> > What is the nature of the changes to the webui code in this PR? It didn't seem related to the PR as it is titled, but maybe I'm just missing it.
> 
> Never mind -- I need to read the PR body not just the title

Hmm...actually the question stands after looking more closely. Just curious.

**Comment by joe-bethke** [comment]
@kyleestes I don't think there are any webui changes here; the changes are to a javascript function that is added to our ASA job for alerting. The change in this PR alters to the ASA job ARM template we use in our CreateSAJob runbook. The javascript changes in the PR description are just an easier way to view the changes to the ARM template.

**Comment by kyleestes** [comment]
Weird -- when I wrote that comment, there were 3 files modified in the webui folder.

**Pull request merged**
