### PR TITLE
fix(webui): removed alarm exception when not exists in COSMOS

### PR DESCRIPTION
**Pull request by viswanadh-kotha**
Hi Team,

This PR includes the changes of removing the exception when we don't have collection in COSMOS.

### CODE REVIEW

**Comment by viswanadh-kotha** [comment]
Joe,
 
Lyle from PSD environment has raised an issue, i.e., Mutiple 404 errors in the UI console.
 
When we figure out the rootcause we found that in PSD environment they are not using alarms collection, so every time we are getting this exception. In order to handle that error we suppressed this error message.

**Comment by joe-bethke** [comment]
I don't think I like the idea of completely suppressing the 404, but I understand Lyle's concern with the 404s in the web console. When I think about potentially debugging anything related to the alarms collection in the future, suppressing the 404 would be detrimental to that process. How are they bypassing the creation of the alarms collection in the first place? The collection is created when using the UI.

**Comment by viswanadh-kotha** [comment]
As per discussion with Joe, closing this PR and we will create new PR after latest changes

**Comment by viswanadh-kotha** [comment]
As per Joe's recommendation, we have updated code by handling api calls from the webui based on the alertign status instead of having suppressing the error message when we dont have collection

**Pull request merged**
